### ISSUE TITLE
undefined reference to `__riscv_flush_icache`

### ISSUE THREAD

**Issue by Gurucharan21** [riscv/riscv-gcc#140]
riscv64-unknown-linux-gnu-gcc -MMD -MP -Wall -Werror -D__NO_INLINE__ -mcmodel=medany -O2 -std=gnu99 -Wno-unused -Wno-attributes -fno-delete-null-pointer-checks  -DBBL_PAYLOAD=\"bbl_payload\" -DBBL_LOGO_FILE=\"bbl_logo_file\" -I. -I../pk -I../bbl -I../softfloat -I../dummy_payload -I../machine -I../util -c ../pk/pk.c
riscv64-unknown-linux-gnu-gcc -nostartfiles -nostdlib -static  -o pk pk.o -L.  -lpk  -lmachine  -lsoftfloat  -lutil -lgcc -T ../pk/pk.lds
/usr/local/lib/gcc/riscv64-unknown-linux-gnu/8.2.0/../../../../riscv64-unknown-linux-gnu/bin/ld: pk.o: in function `.L16':
pk.c:(.text+0x23c): undefined reference to `__riscv_flush_icache'
collect2: error: ld returned 1 exit status
Makefile:302: recipe for target 'pk' failed
make: *** [pk] Error 1

**Comment by jim-wilson** [comment]
I assume you are using riscv-gnu-toolchain.  This is a versioning problem that must be ignored for now.

Glibc is half upstream.  The 64-bit support is upstream, but the 32-bit support is not.  So for now, riscv-gnu-toolchain uses an old obsolete version of riscv-glibc that has both the 32-bit and 64-bit glibc support, but does not have the __riscv_flush_icache support which is an ABI change made just before the 64-bit support was upstreamed.  But riscv-gnu-toolchain does have an up-to-date gcc which requires the __riscv_flush_icache support.  So this is broken, but only in riscv-gnu-toolchain.  We are in the process of upstreaming the 32-bit support now.  When that is finished, riscv-gnu-toolchain will be upgraded to use a copy of the FSF glibc tree, and this will start working again.

Meanwhile, if you want this to work, you must not use riscv-gnu-toolchain.  You either need to use an older gcc that doesn't require __riscv_flush_icache, or a newer glibc (e.g. an FSF glibc) that does have __riscv_flush_icache.  So one way to fix this is to use FSF source trees instead of riscv-gnu-toolchain.  Another way to fix this is to use sifive/freedom-u-sdk which is still using an old version of gcc before the __riscv_flush_icache ABI change.

Another solution is to use a riscv64-unknown-elf-gcc compiler to build pk, because the embedded elf toolchain does use the linux specific __riscv_flush_icache function.

**Comment by sequencer** [comment]
Hi Jim, what's the status of `__riscv_flush_icache` in RV32 now? In GCC 10.2.0, it seems still not upstreamed?

**Comment by jim-wilson** [comment]
rv32 patches were upstreamed in September.  We haven't updated riscv-glibc yet.  We usually do that after a release.  The rv32 patches were added just after the last release in August, so the first release that will include rv32 support will be February 2021.  But I'm not sure of the status of the work.  SiFive does not support rv32-linux.  There are companies using it, but none of those companies are working upstream, so no one is testing upstream support.  It is possible some issues will turn up once someone actually starts using the upstream work.

**Comment by sequencer** [comment]
Thanks JIm for your clarification!
I just wanna use `riscv64-linux-gnu-` toolchain in linux distribution compiling https://github.com/riscv/riscv-tests to ease CI in rocket-chip.
Seems still need to wait until next February.
Or is there any work around you can suggest?

**Comment by jim-wilson** [comment]
You mentioned rv32, now you mentioned rv64.  Is there a problem with the rv64 toolchain?

I don't know if riscv-tests can work with a linux compiler.  It is designed to be used with an embedded elf compiler.

You mentioned linux, but it isn't clear if you mean an x86_64-linux hosted cross compiler, or a native riscv64-linux compiler.  If you want a native riscv64-linux compiler, you should not use riscv-gnu-toolchain.  it isn't designed for that.  You should use the toolchain that comes with the linux distro, or build one natively the normal way.

If you do need a cross compiler, and you need something more recent than what is in riscv-gnu-toolchain, you can always use git remote to pull upstream sources into a riscv-gnu-toolchain tree.  I've mentioned how to do this before, for instance in
https://github.com/riscv/riscv-gnu-toolchain/issues/594
