### ISSUE TITLE
How to get the test result on x86_64-w64-mingw32 ?

### ISSUE THREAD

**Issue by duchao713** [riscv/riscv-gcc#268]
Hi,

I see the gcc-testresults such as https://gcc.gnu.org/legacy-ml/gcc-testresults/2018-05/msg00583.html.

I also want to get my gcc test result for x86_64-w64-mingw32. What commands or configure parameters should be used ?

Thank you.

Best Regards,
DC

**Comment by jim-wilson** [comment]
"make check" in a native gcc build tree will run all of the gcc testsuites.  Since some tests will normally fail, use of -k is recommended to continue after failures.  Adding -j will make it run faster.  If this is a cross compiler, then you need to set up a dejagnu environment that allows the build machine to connect to the target, send over binaries, and then run them.  Or else set up a dejagnu environment to use a simulator.  You may need to install packages like dejagnu, tcl, and expect to get the testsuite working.
