### ISSUE TITLE
some   error for  riscv-gcc 

### ISSUE THREAD

**Issue by Pengnian** [riscv/riscv-gcc#86]
Hi,all 
when  I  want to compile  my  program by riscv-toolchain  some errors happened ,please experts explanation !  thanks ~
![error_1](https://user-images.githubusercontent.com/26727603/29001735-4984174c-7ac5-11e7-9b87-881d0db62f5d.png)
![error_2](https://user-images.githubusercontent.com/26727603/29001736-49af31a2-7ac5-11e7-8e78-4620d2ebe989.png)

**Comment by kito-cheng** [comment]
-march= only accept lowercase letter now, so you could try -march=rv64ima instead of -march=RV64IMA.

-msoft-float is an legacy option which is already removed now, you need specify by -mabi=, I suggest you can use -mabi=lp64 in this case; Here is more detail if you have interesting: argument could begin with ilp32 or lp64 for rv32 or rv64, and it could be suffix with f, d or no suffix, its represent for hard float or soft float abi which mean pass floating point value.

Sorry for such non-backward compatible changes, we promise there is no further non-backward compatible changes.

**Comment by Pengnian** [comment]
@kito-cheng 
Oh,Thanks kito

Your explanation very useful,thanks you again !

**Comment by kito-cheng** [comment]
:)
